source 'http://rubygems.org'

gem 'rails', '3.1.0.rc8'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'
group :development do 
  gem 'sqlite3'
end


gem "sublimevideo_rails"

group :production do 
  gem 'taps'
  gem 'pg'
end

#Needs update
gem 'ffi', '~> 1.0.11'
gem 'therubyracer', '0.10.1'
gem 'libv8', '3.3.10.4'
gem 'json', '1.7.1'

# Asset template engines
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
